package thkoeln.st.springtestlib.specification.table;

public enum TableMismatchCause {
    ROW_NOT_FOUND, COLUMN_NOT_FOUND, NOT_ENOUGH_ROWS, TOO_MANY_ROWS, MISSING_EXPLANATION, CELL_MISMATCH,
    WRONG_COLUMN_MISMATCH, WRONG_ROW_MISMATCH, TOO_MANY_MISMATCH, MISSING_MISMATCH, CAPITALIZATION_MISMATCH
}
